platform :ios, '12.0'

target 'BareBonesDemo2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SocureSdkDemo
    pod 'SocureSdk', :git => 'git@github.com:socure-inc/socure-ios-sdk.git'
end
